# Generated by Django 3.1 on 2021-12-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ip_ordered',
            new_name='is_ordered',
        ),
    ]
